apiVersion: v1
kind: ConfigMap
metadata:
  name: itsm-backend-config
  namespace: incident-linkedeye-itsm
data:
  DATABASE_HOST: "postgresql.postgresql.svc.cluster.local"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "linkedeye_finspot"
  REDIS_HOST: "redis.redis.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  CELERY_BROKER_URL: "redis://redis.redis.svc.cluster.local:6379/1"
  CELERY_RESULT_BACKEND: "redis://redis.redis.svc.cluster.local:6379/2"
  ENVIRONMENT: "production"
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  ALLOWED_HOSTS: '["fs-le-dev-inc.finspot.in","fs-le-dev-inc.api.finspot.in","localhost","127.0.0.1"]'
  ALLOWED_ORIGINS: '["https://fs-le-dev-inc.finspot.in","https://fs-le-dev-inc.api.finspot.in"]'
  RATE_LIMIT_ENABLED: "true"
  PROMETHEUS_URL: "http://prometheus-svc.fs-linkedeye.svc.cluster.local:9090"
  LOKI_URL: "http://loki-svc.fs-linkedeye.svc.cluster.local:3100"
  LOKI_ORG_ID: "fake"
  GRAFANA_URL: "http://grafana-svc.fs-linkedeye.svc.cluster.local:3000"
  STACKSTORM_URL: "https://fs-le-dev-stackstom.finspot.in"
