apiVersion: v1
kind: Secret
metadata:
  name: itsm-backend-secrets
  namespace: incident-linkedeye-itsm
type: Opaque
stringData:
  DATABASE_PASSWORD: "Fin%40spot%21leadmin"
  DATABASE_USER: "root"
  JWT_SECRET_KEY: "CHANGE_ME_IN_PRODUCTION"
  REDIS_PASSWORD: ""
  # OAuth2 secrets
  OAUTH2_CLIENT_ID: "CHANGE_ME"
  OAUTH2_CLIENT_SECRET: "CHANGE_ME"
